### ISSUE TITLE
Replace tab characters with visually different character

### ISSUE THREAD

**Issue by kbilsted** [ezekg/chrome-github-auto-tab-indent#2]
If you have a coding standard where tabs are required over spacing, it would be nice if each tab could be replaced with X-1 spaces, and one character as an arrow (eg. as how tabs are displayed in visual studio)

this makes it easy during review to spot a missing tab (or vice verca, if tabs are forbidden, to detect a slipped in tab character).

**Comment by ezekg** [comment]
This is a cool idea, but I think it's out of the scope of this plugin. This should be something handled by a [linter](http://jshint.com/), before committing to a repository. Right now, this plugin takes advantage of the fact that you can pass in the param `?ts=n` into the url, where `n` is the tab spacing you want. It doesn't actually modify anything on the page, but uses existing features available for the [code editor](https://ace.c9.io/#nav=about) GitHub/Bitbucket use.

**Comment by kbilsted** [comment]
I'm using github for c#,js and f#...so a litter may not be available.  Maybe I'll fork your project and do it myself

**Comment by ezekg** [comment]
Yeah, I think that's something that should be handled by a separate plugin, because it's really a completely different tool. Since you're simply trying to check if the file contains consistent tabs, I'm sure it would be a relatively simple plugin to write. You would have to do some DOM manipulation to insert the symbols in place of the tab characters.

Feel free to fork this and use what I have as a base. Let me know if you need any help.

**Comment by kbilsted** [comment]
I was hoping I could rewrite tab char with an arrow char and some spaces...
Den 04/12/2015 5.55 PM skrev "Ezekiel Gabrielse" notifications@github.com:
